### ISSUE TITLE
Investigate the ingestion performance hit 

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/juno#3]
The ingestion service is slowing down after some time when started.
Thus, currently, we're lagging behind around `16000` blocks, and it's increasing.
So, we need to investigate what is causing this performance hit and fix it.

**Comment by rach-id** [comment]
@evan-forbes Might not be related to this. But I am wondering about the `malleatedTx`:
1. When we make this call: https://github.com/celestiaorg/juno/blob/42a360062f6f6d021af8b491a08ba76957e521c5/node/remote/node.go#L147
it also returns the `unwrappedTx`. This latter is of type `Tx` which is a `[]byte`. Are we able to unmarshal it correctly without making the following call: 
https://github.com/celestiaorg/juno/blob/42a360062f6f6d021af8b491a08ba76957e521c5/node/remote/node.go#L157
which invokes: 
```golang
err := c.cc.Invoke(ctx, "/cosmos.tx.v1beta1.Service/GetTx", in, out, opts...)
``` 
If so, we can do that and avoid extra `rpc` calls.

2. When we add support for `ABCI++`. Then, we would no longer need the `malleatedTx` concept as the `PreprocessTxs` will be done in other methods?

Let me know what you think when you have time. Thanks

**Comment by evan-forbes** [comment]
wow, great digging! yeah, that transaction is the one that we should use, and I don't think making an additional rpc call is needed.

we can see what is wrapped by looking in the PreprocessTxs (soon to be PrepareProposal) method, the transaction wrapped is the `MsgPayForMessage`

https://github.com/celestiaorg/celestia-app/blob/cfe3ecf30837f4d134c4c86aa1547cfc2d706770/app/abci.go#L67-L93

**Comment by rach-id** [comment]
Awesome. And, when we will use `PrepareProposal`, will we still have to wrap/unwrap and get the original hash ? 
If, no need to change anything and just leave until we have that.

**Comment by evan-forbes** [comment]
We will still need to unwrap malleated txs, as `PrepareProposal` is essentially only a rename of `PreprocessTxs`.

We should definitely implement this optimization regardless, as it is easy and makes sense, but do you know how many times this currently gets called? I can't imagine we have too many txs in each block.

**Comment by rach-id** [comment]
It sounds easy, but I don't think it is... It would require making breaking changes with upstream, and that would increase the maintenance cost (we won't be able just to pull upstream and enjoy new features). 
I created an issue in the main repository, and I am waiting to get their feedback on why they didn't implement it that way.

**Comment by rach-id** [comment]
Closing this as we're no longer facing this issue.
The way we're deploying it right now is we're having multiple Celestia nodes with their respective ingestion services running at the same time.
This allows the ingestion services to divide the new blocks and not fall behind.
PS: Using a higher number of workers didn't solve the issue as they were targeting the same Celestia node, and thus it was unable to sync and also service grpc requests.
