### ISSUE TITLE
Pull upstream changes

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/juno#4]
The ingestor has been missing the latest changes. Upstream should be pulled.

**Comment by lzrscg** [comment]
this is done
https://github.com/CelestiaScan/juno/commit/b171a15b7469b50be82bf110854061742ae79467

**Comment by rach-id** [comment]
Thanks a lot for your help. 
Can you please open PRs to Celestia forks containing the changes, so we have an updated  version as well ?
