### ISSUE TITLE
Depend on the latest version of Cosmos-SDK

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/juno#5]
Currently, the ingestor is depending on an old version of the `celestiaorg/cosmos-sdk` fork:
https://github.com/celestiaorg/juno/blob/42a360062f6f6d021af8b491a08ba76957e521c5/go.mod#L41
This should change to depend on: 
```golang
github.com/cosmos/cosmos-sdk => github.com/celestiaorg/cosmos-sdk v1.0.1-sdk-v0.44.2
```

**Comment by rach-id** [comment]
@evan-forbes Please, is `github.com/celestiaorg/cosmos-sdk v1.0.1-sdk-v0.44.2` the latest version to depend on?

**Comment by evan-forbes** [comment]
yeah, that's the tag that we're using. 

soon we will upgrade to [`v1.1.0-sdk-v0.46.0`](https://github.com/celestiaorg/cosmos-sdk/tree/v1.1.0-sdk-v0.46.0), and I think testnet will be using an upgraded version if all goes smoothly

**Comment by rach-id** [comment]
So we just use this version. And when the upgraded version is ready, we move to it. Hopefully, the changes are not that much.

**Comment by lzrscg** [comment]
This is done for juno, but updating dependencies for **bdjuno** is still in-progress. There are several issues that arose
- [x] there was a dependency on rosetta 7, which I was able to [easily make compatible](https://github.com/CelestiaScan/cosmos-sdk/commit/84ab2f08bfe0cb20d1df23fe5cad47c2239baf85#diff-6e97936feda892712f8fb189ae83e769960a2b9b9bb2f417454a26fc8442650dR52) by forking cosmos-sdk.
- [ ] gaia ultimately has a dependency on a different version of cosmos-sdk that has `Events` in `TxResponse` ([like there is in v1.1.0-sdk-v0.46.0](https://github.com/celestiaorg/cosmos-sdk/blob/v1.1.0-sdk-v0.46.0/types/abci.pb.go#L66)). I'm curious if anyone has a recommendation for how to resolve this? [See issue here](https://github.com/CelestiaScan/bdjuno/issues/1)

thoughts and comments are welcome

**Comment by rach-id** [comment]
Thanks a lot for your help.
Concerning this, let's use this for Juno:
```
github.com/cosmos/cosmos-sdk => github.com/celestiaorg/cosmos-sdk v1.0.1-sdk-v0.44.2
```
And for BdJuno, instead of depending on latest master, let's depend on this commit `60800467b1a3bfb8e81367891863f43394b2252d`. This would save us the pain of moving to cosmos-sdk 0.46 which Juno doesn't support.
For now, I guess these versions should be enough:
- cosmos-sdk v1.0.1-sdk-v0.44.2
- celestia-app: this commit: 60800467b1a3bfb8e81367891863f43394b2252d
